project_id = "fllsnsidgqlacdyatvbm"

[functions.hooks]
verify_jwt = false

[functions.reply]
verify_jwt = true

[functions.create-checkout-public]
verify_jwt = false

[functions.is-paid-email]
verify_jwt = false
