project_id = "fllsnsidgqlacdyatvbm"

[functions.hooks]
verify_jwt = false

[functions.reply]
verify_jwt = true

[functions.create-checkout-public]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.is-paid-email]
verify_jwt = false

[functions.validate-twilio]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
